name: "Build and Push Image"
description: "Build and Push Image"
inputs:
  image_name:
    description: 'Image name'
  dockerfile_dir:
    description: 'DockerFile directory'
runs:
    using: "composite"
    steps:
    - name: '登录到阿里云杭州容器镜像服务'
      uses: docker/login-action@v1
      with:
        registry: registry.cn-hangzhou.aliyuncs.com
        username: ${{ secrets.DOCKER_ALI_REGISTRY_USN }}
        password: ${{ secrets.DOCKER_ALI_REGISTRY_PWD }}

    - name: '登录到阿里云北京容器镜像服务'
      uses: docker/login-action@v1
      with:
        registry: registry.cn-beijing.aliyuncs.com
        username: ${{ secrets.DOCKER_ALI_REGISTRY_USN }}
        password: ${{ secrets.DOCKER_ALI_REGISTRY_PWD }}

    - name: '构建镜像并上传到 ghcr.io 容器镜像仓库'
      id: docker_build
      uses: docker/build-push-action@v2
      with:
        context: ${{ inputs.dockerfile_dir }}
        push: true
        tags: ${{ inputs.image_name }}
